### ISSUE TITLE
Create users profile page, single page

### ISSUE THREAD

**Issue by torabian** [owsolutions/angular5-iot-dashboard#89]
We need a page to edit users information, update and manage it's capabilities.

**Comment by muneerh** [comment]
[mu.pdf](https://github.com/smart-dashboard/angular-dashboard/files/1202086/mu.pdf)



this a simple code , if you  want any change contact me

**Comment by muneerh** [comment]
[mu.pdf](https://github.com/smart-dashboard/angular-dashboard/files/1202095/mu.pdf)
here is simple code ,if you want to add or change anything I can contact with me

**Comment by muneerh** [comment]
#89 
here is simple code ,if you want to add or change anything I can contact with me
[mu.pdf](https://github.com/smart-dashboard/angular-dashboard/files/1202096/mu.pdf)
